Collections/Models/ViewModels/CollectionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Collections.Models.ViewModels
{
    public class CollectionViewModel
    {
        [Required]
        public string Name { get; set; }
        public string UserId { get; set; }
        public int FieldNumber { get; set; }
        public int FieldText { get; set; }
        public int FieldTextarea { get; set; }
        public int FieldCheck { get; set; }
        public int FieldDate { get; set; }
    }
}

Collections/Areas/Dashboard/Controllers/CollectionController.cs
using Collections.Models;
using Collections.Services.Admin.Collections;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    [Authorize]
    public class CollectionController : Controller
    {
        private readonly ICollectionService _collectionService;
        private readonly IWebHostEnvironment _env;

        public CollectionController(ICollectionService collectionService, IWebHostEnvironment env)
        {
            _collectionService = collectionService;
            _env = env;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string userId, string sort, string filter, string search, int? page)
        {
            var collections = await _collectionService.GetUserCollectionsAsync(userId ?? User.Identity.Name, sort, filter, search, page);

            ViewData["CurrentSort"] = sort;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sort) ? "name_desc" : "";
            ViewData["CurrentFilter"] = search;

            return View(collections);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AppCollection model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var success = await _collectionService.CreateCollectionAsync(model, User.Identity.Name);
            return success ? RedirectToAction("Index") : View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var collection = await _collectionService.GetCollectionAsync(id);
            return collection == null ? NotFound() : View(collection);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AppCollection model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var success = await _collectionService.UpdateCollectionAsync(model);
            return success ? RedirectToAction("Index") : View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var success = await _collectionService.DeleteCollectionAsync(id);
            return success ? RedirectToAction("Index") : NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Export(string userId)
        {
            var (content, filename) = await _collectionService.ExportCollectionsAsync(userId, _env.WebRootPath);

            if (content == null)
            {
                return RedirectToAction("Index");
            }

            return File(content, "application/octet-stream", filename);
        }
    }
}

Collections/Areas/Dashboard/Views/Collection/Create.cshtml
@model AppCollection

@{ 
	ViewData["Title"] = "Collection Create";
}

<h1 class="font-bold pl-2">Add Collection</h1>

<div class="w-full mt-4">
	<form 
		asp-action="Create" 
		class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
		method="post"
	>
		<div class="mb-4">
			<label class="block text-gray-700 text-sm font-bold mb-2" asp-for="Name"></label>
			<input
				class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
				asp-for="Name"
				type="text" 
			/>
			<span class="block text-red-500 text-sm mb-2" asp-validation-for="Name"></span>
		</div>

		<div class="flex items-center justify-between">
			<button 
				class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" 
				type="submit"
			>
				Save
			</button>
		</div>
	</form>
</div>

Collections/Areas/Dashboard/Views/Collection/Edit.cshtml
@model AppCollection

@{ 
	ViewData["Title"] = "Collection Edit";
}

<h1 class="font-bold pl-2">Edit Collection</h1>

<div class="w-full mt-4">
	<form 
		asp-action="Edit" 
		class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
		method="post"
	>
		<input asp-for="UserId" type="hidden" />
		<div class="mb-4">
			<label class="block text-gray-700 text-sm font-bold mb-2" asp-for="Name"></label>
			<input
				class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
				asp-for="Name"
				type="text" 
			/>
			<span class="block text-red-500 text-sm mb-2" asp-validation-for="Name"></span>
		</div>

		<div class="flex items-center justify-between">
			<button 
				class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" 
				type="submit"
			>
				Save
			</button>
		</div>
	</form>
</div>

Collections/Areas/Dashboard/Views/Collection/Index.cshtml
@model Collections.Utils.PaginatedList<AppCollection>
@{ 
	int i = 0; 
	ViewData["Title"] = "Collections Index";
}
<div class="flex pt-4 justify-end">
	<div class="mr-4">
		<a
			asp-area="Dashboard"
			asp-controller="Collection"
			asp-action="Create"
			class="px-4 py-2 bg-blue-500 text-white rounded"
		>
			Create
		</a>
	</div>
	<div class="mr-7">
		<a
			asp-area="Dashboard"
			asp-controller="Collection"
			asp-action="Export"
			asp-route-userId="@Model.FirstOrDefault()?.User.Id"
			class="px-4 py-2 bg-green-500 text-white rounded"
		>
			Export CSV
		</a>
	</div>
</div>

<div class="flex flex-col">
	<div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
		<div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
			<div>
				<form asp-action="Index" method="get">
					<div class="pl-4">
						<p class="text-lg">
							<span class="font-medium">Find by name:</span>  
							<input 
								type="text" 
								name="search" 
								class="shadow appearance-none border rounded p-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
								valu="@ViewData["CurrentFilter"]"
							/>
							<button type="submit" class="text-white p-1 bg-blue-500 rounded">
								Search
							</button>|
							<a 
								asp-action="Index"
								class="text-blue-500"
							>
								Back to Full List
							</a>
						</p>
					</div>
				</form>
				<table class="min-w-full">
					<thead class="border-b">
						<tr>
							<th scope="col" class="font-bold text-gray-900 px-6 py-4 text-left">
								#
							</th>
							<th scope="col" class="font-bold text-gray-900 px-6 py-4 text-left">
								Name
								<a 
									asp-action="Index" 
									asp-route-sort="@ViewData["NameSortParam"]"
									asp-route-filter="@ViewData["CurrentFilter"]"
								>
									<img class="inline w-4" src="~/images/up-and-down-arrows.svg" />
								</a>
							</th>
							<th scope="col" class="font-bold text-gray-900 px-6 py-4 text-right">
								Actions
							</th>
						</tr>
					</thead>
					<tbody>
						@if (Model.Count > 0)
						{
							@foreach (var collection in Model)
							{
								<tr class="border-b">
									<td class="px-6 py-4 whitespace-nowrap  font-medium text-gray-900">
										@(++i)
									</td>
									<td class=" text-gray-900 px-6 py-4 whitespace-nowrap">
										@collection.Name
									</td>
									<td class="flex justify-end text-gray-900 px-6 py-4 whitespace-nowrap">
										<a 
											asp-area="Dashboard"
											asp-controller="Item"
											asp-action="Create"
											asp-route-collection="@collection.Id"
											class="ml-2 px-4 py-1 rounded bg-blue-500 text-white"
										>
											Add Item
										</a>
										<a
											asp-action="Edit" 
											asp-route-id="@collection.Id"
											class="ml-2 px-4 py-1 rounded bg-green-500 text-white"
										>
											Edit
										</a>
										<a
											asp-action="Delete" 
											asp-route-id="@collection.Id"
											class="ml-2 px-4 py-1 rounded bg-red-500 text-white"
										>
											Delete
										</a>
									</td>
								</tr>
							}
						}
					</tbody>
				</table>
				@{
					var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
					var nextDisabled = !Model.HasNextPage ? "disabled" : "";
				}

				<div class="mt-8">
					<a 
						asp-action="Index"
						asp-route-sort="@ViewData["CurrentSort"]"
						asp-route-page="@(Model.PageIndex - 1)"
						asp-route-filter="@ViewData["CurrentFilter"]"
						class="text-white p-2 mx-2 rounded bg-blue-500 @prevDisabled"
					>
						Previous
					</a>
					<a 
						asp-action="Index"
						asp-route-sort="@ViewData["CurrentSort"]"
						asp-route-page="@(Model.PageIndex + 1)"
						asp-route-filter="@ViewData["CurrentFilter"]"
						class="text-white p-2 mx-2 rounded bg-blue-500 @nextDisabled"
					>
						Next
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script>
		const links = document.querySelectorAll('a')
		if (links) {
			links.forEach(l => {
				if (l.classList.contains('disabled')) {
					l.classList.add(...['cursor-not-allowed', 'pointer-events-none', 'bg-gray-500'])
					l.classList.remove('bg-blue-500')
				}
			})
		}
	</script>
}